scan_filter_chain:

  # 좌측 바퀴 영역 제거 (+80° ~ +100°)

  - name: left_wheel_filter

    type: laser_filters/LaserScanAngularBoundsFilterInPlace

    params:

      lower_angle: 1.40    # +80° (rad)

      upper_angle: 1.75    # +100° (rad)

  # 우측 바퀴 영역 제거 (-100° ~ -80°)

  - name: right_wheel_filter

    type: laser_filters/LaserScanAngularBoundsFilterInPlace

    params:

      lower_angle: -1.75   # -100° (rad)

      upper_angle: -1.40   # -80° (rad)
